ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ com.ideasdeveloper.idc.ApplicationKt.module ];
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/idc"
    url = ${?DB_URL}
    user = "idc"
    user = ${?DB_USER}
    password = "idc_dev_password"
    password = ${?DB_PASSWORD}
    driver = "org.postgresql.Driver"
    maxPoolSize = 10
    maxPoolSize = ${?DB_POOL_SIZE}
}

tenant {
    defaultSchema = "public"
    defaultSchema = ${?DEFAULT_SCHEMA}
}